/*
 * Fechas.java
 */
package net.ausiasmarch.manejofechas.gui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.ausiasmarch.common.Convert;
import java.time.*;
import net.ausiasmarch.manejofechas.modelo.ManejadorFechas;

/**
 * Main.java
 *
 * @author Ariadna Igual
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Fechas
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jTextFieldDia1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDia2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFechaHora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDia = new javax.swing.JTextField();
        jTextFieldMes = new javax.swing.JTextField();
        jTextFieldAnyo = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jTextFieldMinuto = new javax.swing.JTextField();
        jTextFieldSegundo = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jComboBoxUnidades = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSumar = new javax.swing.JButton();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCambiar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldResultado = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonAhora = new javax.swing.JButton();
        jTextFieldAhora = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSemana = new javax.swing.JTextField();
        jButtonRestar = new javax.swing.JButton();
        jButtonLimpiarF = new javax.swing.JButton();
        jButtonLimpiarFH = new javax.swing.JButton();
        jButtonLimpiarTodo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        jLabel11.setText("Dia");

        jLabel12.setText("Dia");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manejo de Fechas");
        setResizable(false);

        jLabel1.setText("Fecha y hora:");

        jLabel2.setText("Dia");

        jLabel3.setText("Mes");

        jLabel4.setText("Año");

        jLabel5.setText("Horas");

        jLabel6.setText("Minutos");

        jLabel7.setText("Segundos");

        jTextFieldDia.setEditable(false);
        jTextFieldDia.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldMes.setEditable(false);
        jTextFieldMes.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldAnyo.setEditable(false);
        jTextFieldAnyo.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldHora.setEditable(false);
        jTextFieldHora.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldMinuto.setEditable(false);
        jTextFieldMinuto.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldSegundo.setEditable(false);
        jTextFieldSegundo.setBackground(new java.awt.Color(204, 204, 255));

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jComboBoxUnidades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Días", "Meses", "Años" }));

        jButtonSumar.setText("Sumar");
        jButtonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha:");

        jLabel9.setText("Añadir/Quitar:");

        jLabel10.setText("Resultado:");

        jTextFieldResultado.setEditable(false);
        jTextFieldResultado.setBackground(new java.awt.Color(204, 204, 255));

        jButtonAhora.setText("Ahora");
        jButtonAhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAhoraActionPerformed(evt);
            }
        });

        jTextFieldAhora.setEditable(false);
        jTextFieldAhora.setBackground(new java.awt.Color(204, 204, 255));

        jLabel13.setText("Día de la semana:");

        jTextFieldSemana.setEditable(false);
        jTextFieldSemana.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldSemana.setText("   ");
        jTextFieldSemana.setToolTipText("");

        jButtonRestar.setText("Restar");
        jButtonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestarActionPerformed(evt);
            }
        });

        jButtonLimpiarF.setText("Limpiar");
        jButtonLimpiarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarFActionPerformed(evt);
            }
        });

        jButtonLimpiarFH.setText("Limpiar");
        jButtonLimpiarFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarFHActionPerformed(evt);
            }
        });

        jButtonLimpiarTodo.setText("Limpiar todos los campos");
        jButtonLimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldResultado)
                            .addComponent(jTextFieldFecha)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonLimpiarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAhora)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAhora, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jTextFieldAnyo))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldHora, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jTextFieldMinuto)
                                            .addComponent(jTextFieldSegundo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(220, 220, 220)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonLimpiarFH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextFieldSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonLimpiarTodo)
                        .addGap(125, 125, 125))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcular))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonLimpiarFH)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAhora)
                            .addComponent(jTextFieldAhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonSumar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRestar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLimpiarF)))
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonLimpiarTodo)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Calcular: Método para desglosar la fecha y hora introducida por el
     * usuario.
     *
     * @param evt
     */
    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        String fechaHora = jTextFieldFechaHora.getText();
        LocalDateTime ldtFechaHora;

        if (!Convert.isValidLocalDateTime(fechaHora)) {
            mensaje("La fecha introducida no es válida.");
            return;
        }

        ldtFechaHora = Convert.parseLocalDateTime(fechaHora);

        int dia = ManejadorFechas.getDia(ldtFechaHora);
        String mes = ManejadorFechas.getMes(ldtFechaHora);
        int anyo = ManejadorFechas.getAnyo(ldtFechaHora);
        int hora = ManejadorFechas.getHora(ldtFechaHora);
        int minuto = ManejadorFechas.getMinuto(ldtFechaHora);
        int segundo = ManejadorFechas.getSegundo(ldtFechaHora);

        jTextFieldSemana.setText(ManejadorFechas.getDiaSemana(ldtFechaHora));
        jTextFieldDia.setText(Convert.format(dia));
        jTextFieldMes.setText(mes);
        jTextFieldAnyo.setText(Convert.format(anyo));
        jTextFieldHora.setText(Convert.format(hora));
        jTextFieldMinuto.setText(Convert.format(minuto));
        jTextFieldSegundo.setText(Convert.format(segundo));

    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * Sumar: Método que suma una cantidad de días, meses o años a la fecha
     * introducida por el usuario.
     *
     * @param evt
     */
    private void jButtonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarActionPerformed
        LocalDate ldFechaHora;
        String fecha = jTextFieldFecha.getText();
        if (!Convert.isValidLocalDateTime(fecha)) {
            mensaje("La fecha introducida no es válida.");
            return;
        }
        ldFechaHora = Convert.parseLocalDate(fecha);

        String sumar = jTextFieldCambiar.getText();
        if (!Convert.isValidInt(sumar)) {
            mensaje("Introduzca una cantidad para sumar válida.");
            return;
        }
        int suma = Convert.parseInt(jTextFieldCambiar.getText());

        String ddmmaa = jComboBoxUnidades.getSelectedItem().toString();

        LocalDate calculo = ManejadorFechas.sumaFecha(ldFechaHora, suma, ddmmaa);
        jTextFieldResultado.setText(Convert.format(calculo));
    }//GEN-LAST:event_jButtonSumarActionPerformed
    /**
     * Restar: Método que resta una cantidad de días, meses o años a la fecha
     * introducida por el usuario.
     *
     * @param evt
     */
    private void jButtonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestarActionPerformed
        LocalDate ldFechaHora;
        String fecha = jTextFieldFecha.getText();
        if (!Convert.isValidLocalDateTime(fecha)) {
            mensaje("La fecha introducida no es válida.");
            return;
        }
        ldFechaHora = Convert.parseLocalDate(fecha);

        String restar = jTextFieldCambiar.getText();
        if (!Convert.isValidInt(restar)) {
            mensaje("Introduzca una cantidad para restar válida.");
            return;
        }
        int resta = Convert.parseInt(jTextFieldCambiar.getText());

        String ddmmaa = jComboBoxUnidades.getSelectedItem().toString();

        LocalDate calculo = ManejadorFechas.restaFecha(ldFechaHora, resta, ddmmaa);
        jTextFieldResultado.setText(Convert.format(calculo));
    }//GEN-LAST:event_jButtonRestarActionPerformed
    /**
     * Ahora: Método que muestra la fecha y la hora en el preciso instante en
     * que se pulsa el botón "Ahora".
     *
     * @param evt
     */
    private void jButtonAhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAhoraActionPerformed
        jTextFieldAhora.setText(ManejadorFechas.fechaAhora());
    }//GEN-LAST:event_jButtonAhoraActionPerformed
    /**
     * LimpiarF Método que limpia/vacía los campos de la sección del cálculo de
     * fechas.
     *
     * @param evt
     */
    private void jButtonLimpiarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarFActionPerformed
        jTextFieldFecha.setText("");
        jTextFieldCambiar.setText("");
        jTextFieldResultado.setText("");
    }//GEN-LAST:event_jButtonLimpiarFActionPerformed
    /**
     * LimpiarFH Método que limpia/vacía los campos de la sección del desglose
     * de la fecha y hora.
     *
     * @param evt
     */
    private void jButtonLimpiarFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarFHActionPerformed
        jTextFieldFechaHora.setText("");
        jTextFieldSemana.setText("");
        jTextFieldDia.setText("");
        jTextFieldMes.setText("");
        jTextFieldAnyo.setText("");
        jTextFieldHora.setText("");
        jTextFieldMinuto.setText("");
        jTextFieldSegundo.setText("");
    }//GEN-LAST:event_jButtonLimpiarFHActionPerformed
    /**
     * LimpiarTodo Método que limpia/vacía todos los campos de la aplicación.
     *
     * @param evt
     */
    private void jButtonLimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarTodoActionPerformed
        // Limpia el apartado de desglose de fecha y hora.
        jTextFieldFechaHora.setText("");
        jTextFieldSemana.setText("");
        jTextFieldDia.setText("");
        jTextFieldMes.setText("");
        jTextFieldAnyo.setText("");
        jTextFieldHora.setText("");
        jTextFieldMinuto.setText("");
        jTextFieldSegundo.setText("");
        // Limpia el apartado del calculo de fechas.
        jTextFieldFecha.setText("");
        jTextFieldCambiar.setText("");
        jTextFieldResultado.setText("");
        // Limpia el apartado de la fecha y hora actual.
        jTextFieldAhora.setText("");
    }//GEN-LAST:event_jButtonLimpiarTodoActionPerformed

    /**
     * Mensaje Método que se encarga de mostrar los mensajes de error por
     * pantalla al usuario.
     *
     * @param mensaje
     */
    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            //No hacemos nada, que se quede como está
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Main fechas = new Main();
                fechas.pack();
                fechas.setLocationRelativeTo(null);
                fechas.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAhora;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLimpiarF;
    private javax.swing.JButton jButtonLimpiarFH;
    private javax.swing.JButton jButtonLimpiarTodo;
    private javax.swing.JButton jButtonRestar;
    private javax.swing.JButton jButtonSumar;
    private javax.swing.JComboBox jComboBoxUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldAhora;
    private javax.swing.JTextField jTextFieldAnyo;
    private javax.swing.JTextField jTextFieldCambiar;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JTextField jTextFieldDia1;
    private javax.swing.JTextField jTextFieldDia2;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldFechaHora;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldMes;
    private javax.swing.JTextField jTextFieldMinuto;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldSegundo;
    private javax.swing.JTextField jTextFieldSemana;
    // End of variables declaration//GEN-END:variables
}
